name: Feature request
description: Propose a new feature or improvement
title: "[feature]: "
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem are you trying to solve?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe the proposed API, behavior, or design.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: What alternatives or workarounds exist today?
    validations:
      required: false

  - type: textarea
    id: impact
    attributes:
      label: Impact / trade-offs
      description: Performance, compatibility, or security considerations.
    validations:
      required: false
